server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    mimetype: application/json
    pretty_print: true
    limit: 10
    # templates: /path/to/templates

logging:
    level: DEBUG
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: GLOSIS WFS3 implementation 
        description: Global Soil Information System
        keywords:
            - GLOSIS
            - soil
            - data
            - api
        keywords_type: theme
        terms_of_service: None
        url: https://glosis.isric.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: ISRIC - World Soil Information
        url: https://isric.org
    contact:
        name: Mendes de Jesus, Jorge Samuel
        position: SDI manager
        address: Droevendaalsesteeg 3
        city: Wageningen
        stateorprovince: Gelderland
        postalcode: 6708 PB
        country: The Netherlands
        phone: +31 317 483 735
        fax: +31 317 483 735
        email: jorge.mendesdejesus@isric.org
        url: https://www.isric.org/contact-us
        hours: 9am to 17pm Central European Time
        instructions: During hours of service.  Off on weekends.
        role: SDI manager

datasets:

    soil_profiles:
        title: Soil Profiles
        description: Soil Profiles for testing GLOSIS
        keywords:
            - soil
            - profile
            - prototype
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.fao.org/global-soil-partnership/pillars-action/4-information-data/glosis/en/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
        provider:
            name: GLOSIS
            table: profile
            data: ../db/soil_data.sqlite
            id_field: id
            mimetype: application/ld+json
# For debug
#    countries:
#        title: Countries in the world
#        description: Countries of the world
#        keywords:
#            - countries
#            - natural eart
#        crs:
#            - CRS84
#        links:
#            - type: text/html
#              rel: canonical
#              title: information
#              href: http://www.naturalearthdata.com/
#              hreflang: en-US
#        extents:
#            spatial:
#                bbox: [-180,-90,180,90]
#            temporal:
#                begin: None
#                end: now  # or empty
#        provider:
#            name: SQLite
#            data: tests/data/ne_110m_admin_0_countries.sqlite
#            id_field: ogc_fid
#            table: ne_110m_admin_0_countries